language: php

os: linux
dist: xenial

php:
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'

branches:
    only:
      - master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - DOCKER_BUILD=false
        - SYMFONY_DEPRECATIONS_HELPER=strict
        - SYMFONY_VERSION=3.4.*

install: travis/install.sh
script: travis/script.sh
after_success: travis/success.sh

jobs:
    include:
        - php: 7.0
          services: [docker]
          env: DOCKER_BUILD=true
        - php: 7.0
          env: SYMFONY_VERSION=3.4.* COMPOSER_PREFER_LOWEST=true
        - php: 7.3
          env: SYMFONY_VERSION=3.4.*
    allow_failures:
        - env: SYMFONY_VERSION=3.4.*@dev

notifications:
    email: samuel.breu@bresam.ch
